### ISSUE TITLE
What about ListViewController with multiple sections？

### ISSUE THREAD

**Issue by atong007** [bhlvoong/LBTATools#22]
It is there a way to use LBTAListController for multiple sections？Except customise the datasource.

**Comment by bhlvoong** [comment]
Nope, ListController only supports a single section.  Supporting multiple sections with varying cell types requires a lot of custom code. Therefore I think writing your own UICollectionViewController subclass is better than using a library.

**Comment by atong007** [comment]
Got it! Thanks.
