### ISSUE TITLE
Compiler Issue for Xcode 10.3

### ISSUE THREAD

**Issue by abiemaxey** [bhlvoong/LBTATools#24]
Hi Brian!
We need support for this.. must remove the default values, thank you!
<img width="1244" alt="Screen Shot 2019-11-21 at 1 02 42 PM" src="https://user-images.githubusercontent.com/14262719/69306028-2b894980-0c61-11ea-9df1-342cf8dd6613.png">

**Comment by bhlvoong** [comment]
I strongly advise updating to Xcode 11+.  This library will only be supported for the latest major version of Xcode.
