### ISSUE TITLE
Amazing, So can I use it in ObjectiveC?

### ISSUE THREAD

**Issue by catalinatCore** [bhlvoong/LBTATools#25]

**Comment by rick2785** [comment]
~~No, this is specifically written for Swift~~ 
I stand corrected.

**Comment by bhlvoong** [comment]
If I recall correctly, you can use Swift libraries in Objective by including a special import.  You can google this quite quickly.

**Comment by catalinatCore** [comment]
> If I recall correctly, you can use Swift libraries in Objective by including a special import. You can google this quite quickly.

Really? Cool！ I'll try.
