### ISSUE TITLE
Problem with Pod Installation

### ISSUE THREAD

**Issue by CodeTeamLabs** [bhlvoong/LBTATools#33]
@bhlvoong 

_**This problem show only I use my real device**_ 

Hi I'm trying to insert LBTA Tools using the **pod 'LBTATools'**

As soon as the pod is installed and I start my app, my app crashes with this error .. where am I wrong?

this is the error

> dyld: Library not loaded: @rpath/LBTATools.framework/LBTATools
>   Referenced from: /private/var/containers/Bundle/Application/5A3136F6-7A0B-4FFC-8080-49A73122A0D2//
>   Reason: no suitable image found.  Did find:
> 	/private/var/containers/Bundle/Application/5A3136F6-7A0B-4FFC-8080-49A73122A0D2//Frameworks/LBTATools.framework/LBTATools: code signature invalid for '/private/var/containers/Bundle/Application/5A3136F6-7A0B-4FFC-8080-49A73122A0D2//Frameworks/LBTATools.framework/LBTATools'
> 
> 	/private/var/containers/Bundle/Application/5A3136F6-7A0B-4FFC-8080-49A73122A0D2//Frameworks/LBTATools.framework/LBTATools: stat() failed with errno=25
> 	/private/var/containers/Bundle/Application/5A3136F6-7A0B-4FFC-8080-49A73122A0D2//Frameworks/LBTATools.framework/LBTATools: code signature invalid for '/private/var/containers/Bundle/Application/5A3136F6-7A0B-4FFC-8080-49A73122A0D2//Frameworks/LBTATools.framework/LBTATools'
> 
> 	/private/var/containers/Bundle/Application/5A3136F6-7A0B-4FFC-8080-49A73122A0D2//Frameworks/LBTATools.framework/LBTATools: stat() failed with errno=1
> 	/private/var/containers/Bundle/Application/5A3136F6-7A0B-4FFC-8080-49A73122A0D2//Frameworks/LBTATools.framework/LBTATools: code signature invalid for '/private/var/containers/Bundle/Application/5A3136F6-7A0B-4FFC-8080-49A73122A0D2//Frameworks/LBTATools.framework/LBTATools'
> 
> 	/private/var/containers/Bundle/Application/5A3136F6-7A0B-4FFC-8080-49A73122A0D2//Frameworks/LBTATools.framework/LBTATools: stat() failed with errno=1

**Comment by bhlvoong** [comment]
Can you go ahead and install LBTATools through Swift Package Manager instead?

**Comment by CodeTeamLabs** [comment]
> Can you go ahead and install LBTATools through Swift Package Manager instead?

hello Brian and thanks for your answer ... I followed some of your videos on youtube and the installation instructions within the github project .. I noticed that the installation is always done via pod ... you have something to do to me see to understand how to use the Swift Package Manager? I don't understand why I can't get LBTA Tools to work on my real device

**Comment by bhlvoong** [comment]
I'm not sure the cause of the pod error, you can try to clean the project and recompile.  The community is already moving away from pods and using SPM more and more. Here's a video on install spm dependencies: https://www.youtube.com/watch?v=ZxHndSGmWcE

**Comment by CodeTeamLabs** [comment]
> I'm not sure the cause of the pod error, you can try to clean the project and recompile. The community is already moving away from pods and using SPM more and more. Here's a video on install spm dependencies: https://www.youtube.com/watch?v=ZxHndSGmWcE

Thank you very much Brian, now with SPM everything seems to work even on my real device!

A small question .. the community is breaking away from the pods so SPM should be used for Firebase too?

**Comment by bhlvoong** [comment]
Excellent. There are a few pods that are still waiting for SPM compatibility and Firebase is one of them.  Because Firebase is such a monstrous sdk, I don't see it supporting SPM anytime soon.  Sad :(

**Comment by CodeTeamLabs** [comment]
> Excellent. There are a few pods that are still waiting for SPM compatibility and Firebase is one of them. Because Firebase is such a monstrous sdk, I don't see it supporting SPM anytime soon. Sad :(


I understand perfectly ... I didn't know SPM and it's beautiful, much faster and lighter ...

Why is the community migrating to SPM?

**Comment by bhlvoong** [comment]
Pods are just messy :)

**Comment by CodeTeamLabs** [comment]
Thanks for all Brian !
