### ISSUE TITLE
issue with target iOS 13 Xcode 11.4

### ISSUE THREAD

**Issue by diegogarciar** [bhlvoong/LBTATools#38]
I just installed the pod on a project targeting iOS 13 and received the following error. XCode 11.4

> 'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.

```
LBTAFormController.swift
@objc fileprivate func handleKeyboardShow(notification: Notification) {
...

   if alignment == .center {
            scrollView.contentInset.bottom += UIApplication.shared.statusBarFrame.height
   }
...
}
```

**Comment by bhlvoong** [comment]
I suggest using SPM instead of pods.

**Comment by diegogarciar** [comment]
I just migrated to SPM, but why the requirement for iOS 11 on layout constraints and ListController?

**Comment by bhlvoong** [comment]
I decided to only support iOS 13+ since there were some major changes with introduction of SwiftUI previews.
