### ISSUE TITLE
how to add button inside the cell with index path.item

### ISSUE THREAD

**Issue by elminawim** [bhlvoong/LBTATools#7]
hi...
thanks a lot for your efforts you are great man ...
i saw all your video in youtube ..

really I have two question 

1) I add button for cell but how can addtarget according the indexpath.item to do my func..

2) can you tell us if we can swap between views lick your youtube app and put in the top tow button to swap between it..

**Comment by bhlvoong** [comment]
github issues is for reporting issues related to this library. This is not an open forum to post questions.
