### ISSUE TITLE
LBTAListHeaderController keep giving fatalError

### ISSUE THREAD

**Issue by Nathan2017** [bhlvoong/LBTATools#8]
I follow the instruction running the basic LBTAListController<MessageCell,UIColor> but keep getting 

required public init?(coder aDecoder:NSCoder) {
fatalError()      
}
Thread 1: Fatal Error

under the LBListHeaderController class pod file

**Comment by bhlvoong** [comment]
I just updated the library to give a better error message.  Basically, remove all files in the Storyboard that use your ListHeaderController class or subclasses.
